CREATE TABLE DEPARTAMENTOS (
    DPTO_COD NUMBER(5) PRIMARY KEY,
    NOMBRE_DPTO VARCHAR2(30) NOT NULL UNIQUE, 
    DPTO_PADRE NUMBER(5),
    PRESUPUESTO NUMBER NOT NULL, 
    PRES_ACTUAL NUMBER,
    CONSTRAINT fk_dpto_padre FOREIGN KEY (DPTO_PADRE) 
        REFERENCES DEPARTAMENTOS(DPTO_COD)
);

CREATE TABLE TRABAJOS (
    TRABAJO_COD NUMBER(5) PRIMARY KEY,
    NOMBRE_TRAB VARCHAR2(20) NOT NULL UNIQUE,
    SALARIO_MIN NUMBER(2) NOT NULL, 
    SALARIO_MAX NUMBER(2) NOT NULL  
);

CREATE TABLE EMPLEADOS (
    DNI NUMBER(8) PRIMARY KEY,
    NOMBRE VARCHAR2(10) NOT NULL, 
    APELLIDO1 VARCHAR2(15) NOT NULL, 
    APELLIDO2 VARCHAR2(15),
    DIRECC1 VARCHAR2(25),
    DIRECC2 VARCHAR2(20),
    CIUDAD VARCHAR2(20),
    PROVINCIA VARCHAR2(20),
    COD_POSTAL VARCHAR2(5),
    SEXO VARCHAR2(1) CHECK (SEXO IN ('H', 'M')),
    FECHA_NAC DATE,
    TELEFONO VARCHAR2(15), 
    CELULAR VARCHAR2(15)   
);

CREATE TABLE UNIVERSIDADES (
    UNIV_COD NUMBER(5) PRIMARY KEY,
    NOMBRE_UNIV VARCHAR2(25) NOT NULL,
    CIUDAD VARCHAR2(20),
    MUNICIPIO VARCHAR2(2),
    COD_POSTAL VARCHAR2(5)
);

CREATE TABLE ESTUDIOS (
    EMPLEADO_DNI NUMBER(8),
    UNIVERSIDAD NUMBER(5),
    ANIO NUMBER,
    GRADO VARCHAR2(3),
    ESPECIALIDAD VARCHAR2(20),
    PRIMARY KEY (EMPLEADO_DNI, UNIVERSIDAD, ANIO), 
    CONSTRAINT fk_estudios_emp FOREIGN KEY (EMPLEADO_DNI) 
        REFERENCES EMPLEADOS(DNI),
    CONSTRAINT fk_estudios_univ FOREIGN KEY (UNIVERSIDAD) 
        REFERENCES UNIVERSIDADES(UNIV_COD)
);

CREATE TABLE HISTORIAL_LABORAL (
    EMPLEADO_DNI NUMBER(8),
    TRABAJO_COD NUMBER(5),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DPTO_COD NUMBER(5),
    SUPERVISOR_DNI NUMBER(8),
    PRIMARY KEY (EMPLEADO_DNI, TRABAJO_COD, FECHA_INICIO),
    CONSTRAINT fk_histlab_emp FOREIGN KEY (EMPLEADO_DNI) 
        REFERENCES EMPLEADOS(DNI),
    CONSTRAINT fk_histlab_trab FOREIGN KEY (TRABAJO_COD) 
        REFERENCES TRABAJOS(TRABAJO_COD),
    CONSTRAINT fk_histlab_dpto FOREIGN KEY (DPTO_COD) 
        REFERENCES DEPARTAMENTOS(DPTO_COD),
    CONSTRAINT fk_histlab_super FOREIGN KEY (SUPERVISOR_DNI) 
        REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE HISTORIAL_SALARIAL (
    EMPLEADO_DNI NUMBER(8),
    SALARIO NUMBER NOT NULL, 
    FECHA_COMIENZO DATE,
    FECHA_FIN DATE,
    PRIMARY KEY (EMPLEADO_DNI, FECHA_COMIENZO), 
    CONSTRAINT fk_histsal_emp FOREIGN KEY (EMPLEADO_DNI) 
        REFERENCES EMPLEADOS(DNI)
);

INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO1, APELLIDO2, SEXO)
VALUES (111222, 'Sergio', 'Palma', 'Entrena', 'H');

INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO1, APELLIDO2, SEXO)
VALUES (222333, 'Lucia', 'Ortega', 'Plus', 'M');

COMMIT;

INSERT INTO DEPARTAMENTOS (DPTO_COD, NOMBRE_DPTO, PRESUPUESTO)
VALUES (1, 'Recursos Humanos', 100000);

INSERT INTO TRABAJOS (TRABAJO_COD, NOMBRE_TRAB, SALARIO_MIN, SALARIO_MAX)
VALUES (1, 'Analista', 10, 50);

INSERT INTO HISTORIAL_LABORAL (EMPLEADO_DNI, TRABAJO_COD, FECHA_INICIO, SUPERVISOR_DNI)
VALUES (111222, 1, TO_DATE('16/06/1996', 'DD/MM/YYYY'), 222333);

COMMIT;

INSERT INTO UNIVERSIDADES (UNIV_COD, NOMBRE_UNIV, CIUDAD)
VALUES (1, 'Universidad Nacional', 'Lima');

COMMIT;

ALTER TABLE ESTUDIOS 
DROP CONSTRAINT fk_estudios_univ;

ALTER TABLE ESTUDIOS 
ADD CONSTRAINT fk_estudios_univ 
    FOREIGN KEY (UNIVERSIDAD) 
    REFERENCES UNIVERSIDADES(UNIV_COD)
    ON DELETE CASCADE;
    
ALTER TABLE EMPLEADOS 
ADD CONSTRAINT chk_ciudad_postal 
    CHECK (CIUDAD IS NULL OR COD_POSTAL IS NOT NULL);

UPDATE EMPLEADOS 
SET COD_POSTAL = '00000' 
WHERE CIUDAD IS NOT NULL AND COD_POSTAL IS NULL;
COMMIT;

-- P11
ALTER TABLE EMPLEADOS 
ADD VALORACION NUMBER(2) DEFAULT 5 
    CHECK (VALORACION BETWEEN 1 AND 10);
-- P12
ALTER TABLE EMPLEADOS 
MODIFY NOMBRE VARCHAR2(10) NULL;
-- P13
ALTER TABLE EMPLEADOS 
MODIFY DIRECC1 VARCHAR2(40);
-- P14
ALTER TABLE EMPLEADOS ADD FECHA_NAC_TEMP VARCHAR2(20);

UPDATE EMPLEADOS 
SET FECHA_NAC_TEMP = TO_CHAR(FECHA_NAC, 'DD/MM/YYYY');

ALTER TABLE EMPLEADOS DROP COLUMN FECHA_NAC;

ALTER TABLE EMPLEADOS RENAME COLUMN FECHA_NAC_TEMP TO FECHA_NAC;
-- P15
ALTER TABLE HISTORIAL_LABORAL DROP CONSTRAINT fk_histlab_emp;
ALTER TABLE HISTORIAL_LABORAL DROP CONSTRAINT fk_histlab_super;
ALTER TABLE HISTORIAL_SALARIAL DROP CONSTRAINT fk_histsal_emp;
ALTER TABLE ESTUDIOS DROP CONSTRAINT fk_estudios_emp;

ALTER TABLE EMPLEADOS DROP PRIMARY KEY;

ALTER TABLE EMPLEADOS 
ADD CONSTRAINT pk_empleados 
    PRIMARY KEY (NOMBRE, APELLIDO1, APELLIDO2);
-- P16
CREATE TABLE INFORMACION_UNIVERSITARIA AS
SELECT 
    E.NOMBRE || ' ' || E.APELLIDO1 || ' ' || E.APELLIDO2 AS NOMBRE_COMPLETO,
    U.NOMBRE_UNIV AS UNIVERSIDAD
FROM 
    EMPLEADOS E
    INNER JOIN ESTUDIOS ES ON E.DNI = ES.EMPLEADO_DNI
    INNER JOIN UNIVERSIDADES U ON ES.UNIVERSIDAD = U.UNIV_COD;

SELECT * FROM INFORMACION_UNIVERSITARIA;
DESC INFORMACION_UNIVERSITARIA;
-- P17
CREATE OR REPLACE VIEW NOMBRE_EMPLEADOS AS
SELECT 
    NOMBRE || ' ' || APELLIDO1 || ' ' || APELLIDO2 AS NOMBRE_COMPLETO
FROM 
    EMPLEADOS
WHERE 
    CIUDAD = 'Málaga';
-- P18
CREATE OR REPLACE VIEW INFORMACION_EMPLEADOS AS
SELECT 
    NOMBRE || ' ' || APELLIDO1 || ' ' || APELLIDO2 AS NOMBRE_COMPLETO,
    TRUNC(MONTHS_BETWEEN(SYSDATE, FECHA_NAC) / 12) AS EDAD
FROM 
    EMPLEADOS;

SELECT * FROM INFORMACION_EMPLEADOS;
-- P19
CREATE OR REPLACE VIEW INFORMACION_ACTUAL AS
SELECT 
    IE.NOMBRE_COMPLETO,
    IE.EDAD,
    HS.SALARIO
FROM 
    INFORMACION_EMPLEADOS IE
    LEFT JOIN HISTORIAL_SALARIAL HS 
        ON IE.NOMBRE_COMPLETO LIKE '%' || 
           (SELECT NOMBRE FROM EMPLEADOS WHERE DNI IN 
               (SELECT EMPLEADO_DNI FROM HISTORIAL_SALARIAL 
                WHERE EMPLEADO_DNI = HS.EMPLEADO_DNI)) || '%'
WHERE 
    HS.FECHA_FIN IS NULL OR HS.FECHA_FIN = 
        (SELECT MAX(FECHA_FIN) FROM HISTORIAL_SALARIAL 
         WHERE EMPLEADO_DNI = HS.EMPLEADO_DNI);
-- P20

DROP TABLE HISTORIAL_SALARIAL CASCADE CONSTRAINTS;
DROP TABLE HISTORIAL_LABORAL CASCADE CONSTRAINTS;
DROP TABLE ESTUDIOS CASCADE CONSTRAINTS;

DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;
DROP TABLE TRABAJOS CASCADE CONSTRAINTS;
DROP TABLE UNIVERSIDADES CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTOS CASCADE CONSTRAINTS;

DROP VIEW INFORMACION_ACTUAL;
DROP VIEW INFORMACION_EMPLEADOS;
DROP VIEW NOMBRE_EMPLEADOS;

DROP TABLE INFORMACION_UNIVERSITARIA;

SELECT table_name FROM user_tables;


